### PR TITLE
Fix cannot import name 'default_rulesdir' from 'ansiblelint'

### LINKED ISSUE #91: cannot import name 'default_rulesdir' from 'ansiblelint'
Hi! 

Recently https://github.com/ansible/ansible-lint was updated from 4.2.0 to 4.3.[0,1].
And now ansible-review don't worked with error:
```
ansible-review --version
Traceback (most recent call last):
  File "/usr/local/bin/ansible-review", line 5, in <module>
    from ansiblereview.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/ansiblereview/__init__.py", line 1, in <module>
    from ansiblelint import default_rulesdir, RulesCollection
ImportError: cannot import name 'default_rulesdir' from 'ansiblelint' (/usr/local/lib/python3.8/site-packages/ansiblelint/__init__.py)
```

I think it may be caused by https://github.com/ansible/ansible-lint/commit/734c6f8e2548c6d02b94f31ef228c86742a50dfb#diff-3a0d2814ee14f24f804a7c3bd1c7863a

### PR DESCRIPTION
**Pull request by kevinkirkup**
Fixes #91. Pin the ansible-lint version.
Current version 4.3.1 refactor *default_rulesdir* away.

### CODE REVIEW

**Review by fivejjs — APPROVED** [review]

**Comment by hahabuknow** [comment]
@kevinkirkup , is this PR can be reviewed and merged?
I also encounter https://github.com/willthames/ansible-review/issues/91 and hope it can be fixed soon.

**Comment by kevinkirkup** [comment]
@hahabuknow It should be. Not sure why it hasn't yet.

**Comment by nphilipp** [comment]
FYI, I've submitted PR #93 which should make pinning the ansible-lint version unnecessary (if applied, of course).
