### ISSUE TITLE
cannot import name 'default_rulesdir' from 'ansiblelint'

### ISSUE THREAD

**Issue by ekbfh** [willthames/ansible-review#91]
Hi! 

Recently https://github.com/ansible/ansible-lint was updated from 4.2.0 to 4.3.[0,1].
And now ansible-review don't worked with error:
```
ansible-review --version
Traceback (most recent call last):
  File "/usr/local/bin/ansible-review", line 5, in <module>
    from ansiblereview.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/ansiblereview/__init__.py", line 1, in <module>
    from ansiblelint import default_rulesdir, RulesCollection
ImportError: cannot import name 'default_rulesdir' from 'ansiblelint' (/usr/local/lib/python3.8/site-packages/ansiblelint/__init__.py)
```

I think it may be caused by https://github.com/ansible/ansible-lint/commit/734c6f8e2548c6d02b94f31ef228c86742a50dfb#diff-3a0d2814ee14f24f804a7c3bd1c7863a

**Comment by kevinkirkup** [comment]
Actually, I think it's this one:
https://github.com/ansible/ansible-lint/commit/55043d6d40c67539abc7f530eff041d052aa28e3

**Comment by kevinkirkup** [comment]
Can you patch this? Ansible-review is completely broken at the moment.
